### ISSUE TITLE
Create sections of cpp programming for realtime and safety.

### ISSUE THREAD

**Issue by ZhenshengLee** [yuchdev/CppBooks#19]
realtime cpp:

https://www.amazon.com/Real-Time-Efficient-Object-Oriented-Microcontroller-Programming/dp/3662478099

safety cpp:

https://www.amazon.com/Secure-Coding-2nd-Software-Engineering/dp/0321822137

**Comment by yuchdev** [comment]
The second one is already present: [Secure Programming Practices](https://github.com/yuchdev/CppBooks#secure-programming-practices).

I added [Real-Time C++: Efficient Object-Oriented and Template Microcontroller Programming](https://www.amazon.com/dp/3662478099). 

Did you read it? Can you add a couple of words as a review? I'm planning review to every single book, which is significant work, so I need some help from the community

**Comment by ZhenshengLee** [comment]
> Did you read it? Can you add a couple of words as a review? I'm planning review to every single book, which is significant work, so I need some help from the community

I will read the book for a bit, and create a PR for this book ASAP.

**Comment by yuchdev** [comment]
It's okay, I already added it. Usually, I add books either I read myself and considered good, or at least several experienced developers consider them good (I'm far from the Embedded industry, so I have to rely on experts' opinions). But the reviews are not bad, so I gave it a try.
You can create a branch with this book review, and we start collecting more detailed information about new books for the community.
