### ISSUE TITLE
Suggestion: API Design for C++ by Martin Reddy 

### ISSUE THREAD

**Issue by bjornblissing** [yuchdev/CppBooks#6]
*API Design for C++* by Martin Reddy 
ISBN: 978-0123850034
https://www.amazon.com/gp/product/B004NNUZ6O/

**Comment by yuchdev** [comment]
I will research about it.
Have you read it? How's your judgment?

**Comment by bjornblissing** [comment]
Yes, I have read it. I would not say that it is a *must read*, but it is certainly worth the read for anyone considering developing an API in C++. It should probably be listed in the **"Software Design and Design Patterns in C++"** category.

**Comment by yuchdev** [comment]
Added
